### ISSUE TITLE
Question ?

### ISSUE THREAD

**Issue by gmonk** [tsujimic/ftpclient-go#1]
Thanks for this library  its been the most flexible and user friendly one I have found so far.  My question is does this support FTPS ?  if so could what modes implicit/explicit ?  could you provide a small example 

Thanks

**Comment by tsujimic** [comment]
Thanks for using it.
It is an old source code, so I have already forgotten some parts.
Regarding FTPS, unfortunately, we do not support explicit mode.
For implicit mode, please refer to the ftpclient_test.go file, which is commented, but has the code to run it.

**Comment by gmonk** [comment]
Thank you.
